// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutritional_Infomation_Calculator.Data;

#nullable disable

namespace Nutritional_Infomation_Calculator.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20240129031716_Restructed Menu Item")]
    partial class RestructedMenuItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nutritional_Infomation_Calculator.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Nutritional_Infomation_Calculator.Models.MenuItem", b =>
                {
                    b.OwnsOne("Nutritional_Infomation_Calculator.Models.Nutrition", "Nutrition", b1 =>
                        {
                            b1.Property<int>("MenuItemMenuId")
                                .HasColumnType("int");

                            b1.HasKey("MenuItemMenuId");

                            b1.ToTable("MenuItems");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemMenuId");

                            b1.OwnsMany("Nutritional_Infomation_Calculator.Models.Nutrient", "Nutrients", b2 =>
                                {
                                    b2.Property<int>("NutritionMenuItemMenuId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<double>("Amount")
                                        .HasColumnType("float");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<double>("PercentOfDailyNeeds")
                                        .HasColumnType("float");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("NutritionMenuItemMenuId", "Id");

                                    b2.ToTable("Nutrient");

                                    b2.WithOwner()
                                        .HasForeignKey("NutritionMenuItemMenuId");
                                });

                            b1.Navigation("Nutrients");
                        });

                    b.OwnsOne("Nutritional_Infomation_Calculator.Models.Servings", "Servings", b1 =>
                        {
                            b1.Property<int>("MenuItemMenuId")
                                .HasColumnType("int");

                            b1.Property<double>("Number")
                                .HasColumnType("float");

                            b1.Property<double>("Size")
                                .HasColumnType("float");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MenuItemMenuId");

                            b1.ToTable("MenuItems");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemMenuId");
                        });

                    b.Navigation("Nutrition")
                        .IsRequired();

                    b.Navigation("Servings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
